/**
 * KotlinAPI
 * KotlinAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gr-kotlinB2020@wpi.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class GetChoiceResponse (
  uniqueID: String,
  alternatives: Seq[Alternative],
  users: Int,
  description: String,
  finalChoice: Alternative,
  hasFinalChoice: Boolean
) extends ApiModel


